Expose kube-controllers prometheus metrics
tigera/operator pull request #1190
Opened 2021-02-26 23:33 UTC by caseydavenport

## Description

These were added in Calico v3.18, will be present in Calico Enterprise v3.6.

This PR enables scraping of these metrics by default in Calico
Enterprise.

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

2021-03-02 18:46 UTC, tmjd commented on pkg/render/kube-controllers.go
> +				// TODO: Users can change this value in KubeControllersConfiguration. We should
Wouldn't it be relatively easy to watch KubeControllersConfiguration and read this field. Is there a good reason to not do that yet?

2021-03-02 22:27 UTC, tmjd requested changes
I think one issue.
This will probably require a ClusterRole update to the docs.

2021-03-02 22:27 UTC, tmjd commented on pkg/render/kube-controllers.go
> +					TargetPort: intstr.FromInt(int(9094)),
Isn't the TargetPort the one that would need to change?
I'm not sure if we should set both to the values configured or just the TargetPort, probably just the TargetPort but whatever you think is best.

2021-03-02 23:11 UTC, caseydavenport commented
@tmjd ready for a final look!

> This will probably require a ClusterRole update to the docs.

Yep, definitely. Have submitted PR here for that: https://github.com/projectcalico/calico/pull/4438

2021-03-03 14:18 UTC, tmjd approved these changes
LGTM

2021-03-03 14:19 UTC, tmjd commented
Though it seems like several tests are failing that will need to be fixed.

2021-03-03 18:16 UTC, merged