FIPS changes for Elastic.
tigera/operator pull request #2115
Opened 2022-08-10 22:51 UTC by rene-dekker

- Adds init container for FIPS
- Moved resource requirements code up, so vm arguments can be parsed more easily
- Added image ending with -fips for elasticsearch, similar to how cni is done

2022-08-10 22:54 UTC, hjiawei commented on pkg/render/logstorage.go
> +	keystoreInitContainerName = "elastic-internal-init-jvm-keystore"
call it `elastic-internal-init-keystore` (remove `jvm`)?

2022-08-10 22:57 UTC, hjiawei commented on pkg/render/logstorage.go
> +	keystoreInitScript        = `#!/usr/bin/env bash
Move this script template into a template file and use [go embed](https://pkg.go.dev/embed)?

2022-08-10 22:59 UTC, hjiawei commented on pkg/render/logstorage.go
> +			"-Djavax.net.ssl.trustStore=/usr/share/elasticsearch/config/cacerts.bcfks"+
nit. space after `cacerts.bcfks` and also update that in your UT.

2022-08-10 23:01 UTC, hjiawei commented on pkg/render/logstorage.go
> +bin/elasticsearch-keystore create -p <<EOF
nit. we can use the absolute path `/usr/share/elasticsearch/bin/elasticsearch-keystore` in case the `WORKDIR` is changed in the future.

2022-08-17 16:19 UTC, Brian-McM requested changes

2022-08-17 16:19 UTC, Brian-McM commented on pkg/render/logstorage.go
> +			Command: []string{"/usr/bin/env", "bash", "-c", fmt.Sprintf(KeystoreInitScript, ElasticsearchKeystoreEnvName, ElasticsearchKeystoreEnvName, ElasticsearchKeystoreEnvName)},
I can't say I'm a fan of this, I don't think we should be generating these containers on the fly and I don't think the code should live in the operator (the operator is basically injecting code into the container).

If the contents of `KeystoreInitScript` are needed to run the container, then I think it should be a part of the container.

2022-08-17 16:19 UTC, Brian-McM commented on pkg/render/embed/initialize_keystore.sh
> +#!/usr/bin/env bash
I can't say I'm a fan of this living in the operator, I don't believe we should be injecting bash commands into any container from the operator (this is more than just configuring a container to run).

If this is needed to run, then either create a separate init container to run, or add it to the elasticsearch container and put it behind a flag or env variable.

2022-08-18 19:04 UTC, Brian-McM approved these changes

2022-08-18 19:54 UTC, hjiawei approved these changes

2022-08-18 21:10 UTC, merged