Compliance multi-tenant changes
tigera/operator pull request #3111
Opened 2024-01-11 16:58 UTC by Josh-Tigera

## Description

## For PR author

- [x] Tests for change.
~- [ ] If changing pkg/apis/, run `make gen-files`~
~- [ ] If changing versions, run `make gen-versions`~

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

2024-01-12 20:35 UTC, caseydavenport requested changes
Looking good! A few relatively minor comments. Main one is re: how network policy is structured.

2024-01-15 16:23 UTC, Josh-Tigera commented on pkg/render/compliance.go
> +func createComplianceSourceEntityRule(deploymentName string, tenantNamespaces []string) v3.EntityRule {
Ah ok I didn't know about this I'll make this reversion. My original intent with passing through all tenant namespaces was to make rules work for components that didn't support multi-tenancy yet but would still run in a multi-tenant cluster, but you mentioned guardian is managed cluster only and dex we don't need  to support multi-tenancy at all so I can just get rid of this pattern entirely.

2024-01-16 20:38 UTC, caseydavenport requested changes
A few more small things. Looks like you have a couple of unused TenantNamespaces fields left over from earlier commits as well.

2024-01-16 20:38 UTC, caseydavenport commented on pkg/controller/compliance/compliance_controller.go
> +		opts = append(opts, certificatemanager.WithTenant(tenant))
The `WithTenant` option actually handles a nil tenant behind the scenes, so no need for the `tenant != nil` check here.

2024-01-16 20:38 UTC, caseydavenport commented on pkg/controller/compliance/compliance_controller.go
> +		opts = append(opts, certificatemanager.WithTenant(tenant))
Would be nice to include a `WithLogger` option here to pass the reqLogger context logger.

2024-01-16 20:38 UTC, caseydavenport commented on pkg/render/manager.go
> +	TenantNamespaces []string
@Josh-Tigera still need to remove this field ^

2024-01-16 20:38 UTC, caseydavenport commented on pkg/controller/manager/manager_controller.go
> +	tenantNamespaces, err := utils.TenantNamespaces(ctx, r.client)
I don't think this is needed any more

2024-01-16 20:38 UTC, caseydavenport commented on pkg/controller/manager/manager_controller.go
> +		TenantNamespaces:        tenantNamespaces,
nor this

2024-01-16 20:38 UTC, caseydavenport commented on pkg/render/compliance.go
> +const ComplianceServerPort = 5443
Does this need to be public now? I can't see where it's used outside of this package (but might have missed something)

2024-01-16 20:38 UTC, caseydavenport commented on pkg/render/logstorage/linseed/linseed.go
> +	TenantNamespaces []string
@Josh-Tigera same here - can remove this field from the struct now

2024-01-17 15:58 UTC, marvin-tigera commented
Removing "merge-when-ready" label due to new commits

2024-01-17 17:40 UTC, marvin-tigera commented
Removing "merge-when-ready" label due to new commits

2024-01-22 18:31 UTC, caseydavenport commented on pkg/controller/compliance/compliance_controller.go
> +	err = complianceController.Watch(&source.Kind{Type: &operatorv1.Compliance{}}, &handler.EnqueueRequestForObject{})
I think this needs to be `eventHandler`

2024-01-22 18:54 UTC, caseydavenport commented on pkg/render/guardian.go
> +			Source:      networkpolicy.CreateSourceEntityRule(ComplianceNamespace, ComplianceBenchmarkerName),
I think for all of these single-tenant packages, you just want to use the `DefaultHelper` - https://github.com/Josh-Tigera/operator/blob/691931ed32299b33efcbd98c8c69d8b49f1ba760/pkg/render/common/networkpolicy/networkpolicy.go#L205

This way we still follow the same code path for single / multi-tenant code.

2024-01-22 18:55 UTC, merged