Operator rbac
tigera/operator pull request #3630
Opened 2024-12-03 23:01 UTC by vara2504

## Description

## For PR author

- [ ] Tests for change.
- [ ] If changing pkg/apis/, run `make gen-files`
- [ ] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [ ] Milestone set according to targeted release.
- [ ] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

2024-12-13 23:30 UTC, rene-dekker approved these changes
lgtm

2024-12-13 23:34 UTC, rene-dekker commented on pkg/render/monitor/monitor.go
> +	toCreate = append(toCreate, render.CreateOperatorSecretsRoleBinding(common.TigeraPrometheusNamespace))
On line 239 we may be creating a secret for which the operator requires permissions. Should we render a binding in that namespace prior to rendering the secret?

2024-12-13 23:35 UTC, rene-dekker requested changes
See the comment in monitor.go

2024-12-17 00:05 UTC, rene-dekker approved these changes

2024-12-17 00:05 UTC, rene-dekker commented
/merge-when-ready

2024-12-17 00:05 UTC, marvin-tigera commented
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

2024-12-17 00:15 UTC, merged